;;; goto-line-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from goto-line-preview.el

(autoload 'goto-line-preview "goto-line-preview" "\
Preview goto line." t)
(autoload 'goto-line-preview-relative "goto-line-preview" "\
Preview goto line relative." t)
(define-obsolete-function-alias 'goto-line-preview-goto-line 'goto-line-preview "0.1.1")

;;; End of scraped data

(provide 'goto-line-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; goto-line-preview-autoloads.el ends here
