;;; makefile-executor-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from makefile-executor.el

(autoload 'makefile-executor-execute-target "makefile-executor" "\
Execute a Makefile target from FILENAME.

FILENAME defaults to current buffer.

(fn FILENAME &optional TARGET)" t)
(autoload 'makefile-executor-execute-project-target "makefile-executor" "\
Choose a Makefile target from all of the Makefiles in the project.

If there are several Makefiles, a prompt to select one of them is shown.
If so, the parent directory of the closest Makefile is added
as initial input for convenience in executing the most relevant Makefile." t)
(autoload 'makefile-executor-execute-dedicated-buffer "makefile-executor" "\
Runs a makefile target in a dedicated compile buffer.

The dedicated buffer will be named \"*<target>*\".  If
`projectile' is installed and the makefile is in a project the
project name will be prepended to the dedicated buffer name.

(fn FILENAME &optional TARGET)" t)
(autoload 'makefile-executor-execute-last "makefile-executor" "\
Execute the most recently executed Makefile target.

If none is set, prompt for it using
`makefile-executor-execute-project-target'.  If the universal
argument is given, always prompt.

(fn ARG)" t)
(autoload 'makefile-executor-goto-makefile "makefile-executor" "\
Interactively choose a Makefile to visit." t)

;;; End of scraped data

(provide 'makefile-executor-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; makefile-executor-autoloads.el ends here
