;;; eshell-did-you-mean-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from eshell-did-you-mean.el

(autoload 'eshell-did-you-mean-setup "eshell-did-you-mean" "\
`eshell-did-you' setup.")

;;; End of scraped data

(provide 'eshell-did-you-mean-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eshell-did-you-mean-autoloads.el ends here
