;;; helm-c-yasnippet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from helm-c-yasnippet.el

(autoload 'helm-yas-complete "helm-c-yasnippet" "\
List of yasnippet snippets using `helm' interface." t)
(autoload 'helm-yas-visit-snippet-file "helm-c-yasnippet" "\
List of yasnippet snippet files" t)
(autoload 'helm-yas-create-snippet-on-region "helm-c-yasnippet" "\
Create a snippet from region.

(fn &optional START END FILE-NAME)" t)

;;; End of scraped data

(provide 'helm-c-yasnippet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-c-yasnippet-autoloads.el ends here
